### ISSUE TITLE
Received an error on terraform plan call

### ISSUE THREAD

**Issue by bpancost** [arri-cc/code-challenge#1]
Hello @arri-cc , this is Brandon from Lucky Day. I ran into the following error calling `terraform plan -out aws.plan`.
Error: Error refreshing state: 1 error(s) occurred:
* data.aws_route53_zone.zone: 1 error(s) occurred:
* data.aws_route53_zone.zone: data.aws_route53_zone.zone: no matching Route53Zone found

Can you please either update your code with a fix or tell me what to configure to get past this step?

**Comment by arri-cc** [comment]
@bpancost I should've been more explicit in the readme, but the s3 bucket used for terraform state management and the Route53 DNS zone need to already exist in the target region.  This was the easiest option for me since my DNS is hosted with DNSimple, I did not want to add that external dependency.

I referenced it here: https://github.com/arri-cc/code-challenge#aws-resources

**Comment by bpancost** [comment]
@arri-cc Can you update the readme file to be more explicit about the steps I would need to take to be able to run your code?

**Comment by arri-cc** [comment]
@bpancost yes

**Comment by arri-cc** [comment]
@bpancost I've made the following changes:

- updated the readme for clarity
- reorganized the terraform variables so you know what values to customize in the sample `terraform.tfvars.sample` file that are unique to your environment

**Comment by arri-cc** [comment]
i also just added a few lines on how to teardown the infrastructure.

**Comment by bpancost** [comment]
@arri-cc Thanks for the quick turnaround!

**Comment by arri-cc** [comment]
@bpancost i spotted an issue with the asg stack and the scripts to make it easy to swap between the health check steps.  I'll push an update later when I get back to my workstation.

**Comment by arri-cc** [comment]
@bpancost I just pushed some updates to simplify things further and address an issue with the ASG rolling updates.

you can now use these quick steps to get up and running, something I should've done in the first place.

https://github.com/arri-cc/code-challenge#tldr-quick-deployment-and-teardown-with-scripts

let me know if you have any other questions.  I'll close this issue.

**Comment by arri-cc** [comment]
@bpancost just a heads up, I resolved issue #2, that would prevent perform a successful `terraform destroy` operation due to orphaned ENIs still attached to the subnets and security groups.  If you ran the plan yesterday there will be interfaces that need to be manually deleted.
